import { EB_Garamond, Caveat } from "next/font/google";
import "./globals.css";
// const ebGaramond = EB_Garamond({ subsets: ["latin"], display: "swap" });
// const caveat = Caveat({ subsets: ["latin"], display: "swap" });
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ebGaramond",
});
const caveat = Caveat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-caveat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("hello world");
  return (
    <html lang="en">
      <body className={caveat.className}>{children}</body>
    </html>
  );
}
